server:
  port: 8080
  servlet:
    context-path:


spring:
  #DatasourceProperties----> mysql
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: SFYchangeme150012.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 15
      min-idle: 15
      max-active: 15
      max-wait: 6000
#      配置邮箱
  mail:
    host: smtp.sina.com
    port: 465
    username: fengofcommunity@sina.com
    password: d3e5dd751244739b #这个是授权密码,不是自己登录密码,一定注意！！！
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
           enable: true


  thymeleaf:
    cache: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.feng.mybatisplusgenerator.entity
  configuration:
    use-generated-keys: true #自动生成id
    mapUnderscoreToCamelCase: true

#

#设置日志级别,简单配置
#logging:
#  level:
#    com.feng.community: info
#  appenders:
#    - type: TransactionConsole
#      threshold: INFO
#      logFormat: "%d{yyyy-MM-dd HH:mm:ss SSS} %-5p [%c][%t] - %m%n"
#    - type: Sizefile
#      threshold: INFO
#      logFormat: "%d{yyyy-MM-dd HH:mm:ss SSS} %-5p [%c][%t] - %m%n"
#      currentLogFilename: /home/log/app.log
#      archivedLogFilenamePattern: /home/zip/app-%i.log.gz
#      maxFileSize: 200MB
#      archivedFileCount: 20
#      timeZone: UTC
#    - type: socketJson
#      threshold: INFO
#      autoDiscover: true
#      logstashServiceName: commsrvlogstash
#      logstashServiceVersion: v1


# community

community:
  path:
    domain: http://localhost:8080
